# Generated by Django 3.2.18 on 2023-03-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0008_alter_playlist_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
    ]
